packages:
  - .
  - packages/*
  - miniapp
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  '@tarojs/binding': false
  '@tarojs/cli': false
  core-js: false
  core-js-pure: false
  esbuild: false
  swiper: false
